module.core-contracts=modules/core/contracts
module.f1-provisioning=modules/feature/provisioning
module.f2-camera-ocr=modules/feature/camera-ocr
module.f3-text-postprocess=modules/feature/text-postprocess
module.f4-dictionary=modules/feature/dictionary
module.f5-tts=modules/feature/tts
module.f6-performance=modules/core/performance
module.integration-tests=modules/integration/tests
module.app=app
asset.tts.models=modules/feature/tts/models
